##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/w3safjt/public_html
    - /bin/cp -R .vscode $DEPLOYPATH
  # iam working in it 
    /bin/cp * $DEPLOYPATH